---
- name: Build and Push Docker image on Master
  hosts: master
  vars:
    docker_registry: 211.183.3.199
    image_name: leejoohyun/project
    image_tag: latest
  tasks:
    # PlayBook 복사하기
    - name: Copy Ansible Playbook to Master
      copy:
        src: "{{ playbook_dir }}/playbook.yml"
        dest: /root/jen/playbook.yml

    # Deploy용 yml 복사하기
    - name: Copy Ansible Deploy to Master
      copy:
        src: "{{ playbook_dir }}/testpod.yml"
        dest: /root/jen/testpod.yml

    # Docker 레지스트리에 로그인하기
    - name: Log in to Docker Registry
      command: docker login "{{ docker_registry }}" -u admin -p test123

    # Docker 이미지를 빌드하고 푸시하기
    - name: Build Docker image
      docker_image:
        build:
          path: /root/jen/subject_option
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"

    - name: Push Docker image to Docker Registry
      docker_image:
        name: "{{ docker_registry }}/{{ image_name }}"
        tag: "{{ image_tag }}"
        push: yes
        login:
          username: admin
          password: test123

    # Kubernetes Deployment 적용
    - name: Apply Deployment
      k8s:
        kubeconfig: /root/.kube/config
        state: present
        definition: /root/jen/testpod.yml
